import ROUTES from "./routes";
import TEXT from "./text";

const PROJECT_NAV = [
	{
		TITLE: TEXT.PROJECT_NAV.PROJECT_DESCRIPTION,
		REF: ROUTES.PROJECT_DESCRIPTION
	},
	{
		TITLE: TEXT.PROJECT_NAV.TEAM_AND_ALUMNI,
		REF: ROUTES.TEAM
	},
	{
		TITLE: TEXT.PROJECT_NAV.JOIN_OUR_TEAM,
		REF: ROUTES.JOIN_OUR_TEAM
	},
	{
		TITLE: TEXT.PROJECT_NAV.RESOURCES,
		REF: ROUTES.RESOURCES
	}

];

export default PROJECT_NAV;
