import ROUTES from "./routes";
import TEXT from "./text";

const PROJECT_NAV = [
	{
		TITLE: TEXT.PROJECT_NAV.PROJECT_DESCRIPTION,
		REF: ROUTES.PROJECT_DESCRIPTION
	},
	{
		TITLE: TEXT.PROJECT_NAV.SUBPAGE1,
		REF: ROUTES.SUBPAGE1
	},
	{
		TITLE: TEXT.PROJECT_NAV.SUBPAGE2,
		REF: ROUTES.SUBPAGE2
	},
	{
		TITLE: TEXT.PROJECT_NAV.TEAM_AND_ALUMNI,
		REF: ROUTES.TEAM
	},
	{
		TITLE: TEXT.PROJECT_NAV.JOIN_OUR_TEAM,
		REF: ROUTES.JOIN_OUR_TEAM
	},
	{
		TITLE: TEXT.PROJECT_NAV.RESOURCES,
		REF: ROUTES.RESOURCES
	},
	{
		TITLE: TEXT.PROJECT_NAV.PROJECT_TIMELINE,
		REF: ROUTES.PROJECT_TIMELINE
	}

];

export default PROJECT_NAV;
