
import MissionStatement from '@components/MissionStatement';
import Card from '@components/Card';
import { TEXT } from '@statics'
import Head from 'next/head'
import Image from 'next/image'
import HeroSection from '@components/HeroSection';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="Home">
      <HeroSection/>
      <div className="card-section">
        <div className="card-container">
          <Card title="Card Title" desc="Description of how the lab can help COGS students with this project" />
          <Card title="Card Title" desc="Description of how the lab can help COGS students with this project" />
          <Card title="Card Title" desc="Description of how the lab can help COGS students with this project" />
          <Card title="Card Title" desc="Description of how the lab can help COGS students with this project" />
        </div>
      </div>
      <div className="mission-statement-container">
        <div className="mission-statement-title">
            <p>{TEXT.LANDING_PAGE.MISSION_STATEMENT.TITLE}</p>
            <div className="title-underline"></div>
        </div>
        <div className="mission-statement-text">
          <p className="mission-statement">{TEXT.LANDING_PAGE.MISSION_STATEMENT.LAB_GOALS}</p>
          <p className="mission-statement">{TEXT.LANDING_PAGE.MISSION_STATEMENT.LAB_GOALS}</p>
        </div>
      </div>
      <div className="mission-img-container">
        <div className="mission-img-placeholder-one"></div>
        <div className="mission-img-placeholder-two"></div>
      </div>
      <MissionStatement />
    </div>
    </>
  )
}
