name: linting check

on: 
  push:
    branches: [ arpit/pr-workflow-new ]
  pull_request:
    branches: [ main ]

jobs: 
  run_eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run lint